version: '2'

services:
  orders:
    container_name: orders_microservice
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env    
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - inventory
      - rabbitmq
    volumes:
      - ./:/usr/src/app
      - ./usr/src/app/node_modules    
    ports:
      - '3000:3000'

  inventory:
    container_name: inventory_microservice
    build:
      context: .
      dockerfile: ./apps/inventory/Dockerfile
      target: development
    command: npm run start:dev inventory
    env_file:
      - ./apps/inventory/.env    
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq
    volumes:
      - ./:/usr/src/app
      - ./usr/src/app/node_modules 

  rabbitmq:
    image: rabbitmq   
    container_name: rabbitmq_microservice
    ports:
      - '5672:5672'

  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_DISABLE_SYSTEM_LOG=true
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - '27020:27017'

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_DISABLE_SYSTEM_LOG=true

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_DISABLE_SYSTEM_LOG=true


volumes:
  mongodb_master_data:
    driver: local
